### ISSUE TITLE
Why this line of code arose in?

### ISSUE THREAD

**Issue by fuzexin** [adrianderstroff/realtime-clouds#2]
`CUBEMAP_PATH = "./assets/images/cubemap/"`
Forgive me i dont use go language, but by roughly seeing, this line  has no use, and there is no cubemap Folder. perhapse is my miss.

**Comment by adrianderstroff** [comment]
Hi fuzexin, you are right, it's not in use. I started this project by copying the code of another project of mine. This line is simply a copy-paste artifact that I haven't deleted yet.
